### ISSUE TITLE
dropdown with emoji for marking notes as important, optional, etc.

### ISSUE THREAD

**Issue by apoapostolov** [pyrige/fvtt-keikaku#1]
The emoji dropdown supports few keywords: Important, Optional for now. Each choice colors the entry in dark red or dark blue hue to make it more recognizable.

**Comment by pyrige** [comment]
I like the idea, I'll give it some thought and try to come up with a decent selection of icons and colors.

**Comment by pyrige** [comment]
I added the possibility to select arbitrary colors for tasks.
In addition, tasks can now be categorized as important or optional and are then prefixed with an appropriate icon.
Both of these settings are optional and default to no icon and the regular text color.

![image](https://user-images.githubusercontent.com/10303076/108505276-6b513d80-72b7-11eb-9407-76e0b0111995.png)

**Comment by pyrige** [comment]
I wasn't all that happy with the icons.
Instead you can now configure a tag for each item:
![image](https://user-images.githubusercontent.com/10303076/110101318-a9fcf280-7da3-11eb-9df5-46d4dc238db1.png)

**Comment by apoapostolov** [comment]
This is much better. Thank you!!
