### ISSUE TITLE
Show Keitaku for each user when they log in for a first time

### ISSUE THREAD

**Issue by apoapostolov** [pyrige/fvtt-keikaku#2]
Because some new players may forget they have notes or not make them part of their ongoing habit, it would be nice if their Keitaku opens up every time they login in the Foundry world.

**Comment by pyrige** [comment]
Good news, that's exactly what 0.1.4 added ;)

By default, a dialog will pop up reminding people of unfinished tasks.
They then can change the setting to either have it pop up regardless of unfinished tasks or never.
Maybe it makes sense to have it default to always so people see it at least once?
