### ISSUE TITLE
Feature request: Add options to share your plans with the gm

### ISSUE THREAD

**Issue by connery0** [pyrige/fvtt-keikaku#4]
This is a great module, but I feel like it would be nice if the GM could check what players plans are so they can help set it up.  
Ideally there would still be a private option so players can keep some of their plots a secret.

**Comment by pyrige** [comment]
Depending on how you imagine it to work, that might not be all that hard to implement.
I imagine we could add a drop down to the GM view for selecting other players.
It's certainly feasible to add a "share with GM" setting that players can opt into.

**Comment by apoapostolov** [comment]
@pyrige it could be just pop up on the GM's screen, like "hey GM, check if I forgot something to add on this list". The GM can make changes to the player's contents if needed, and then closes it. Then it can be accessed by GM only if the player shares with GM again.

**Comment by Ulvtand** [comment]
I think the above suggestions are great. I also want the opportunity to share To Do with other players not just with GM. Suggested solution: use the same solution as with "Completed" to share To Do with other players and GM.

**Comment by pyrige** [comment]
The current version (0.2.0) lets the GM view other players' to-do lists. There's a task setting for keeping certain objectives secret.

Right now, other players cannot check the to-do list and GMs can't modify the items. I'll consider adding those options.

**Comment by pyrige** [comment]
I'll close this for now as the initial request should be satisfied. But I also created #6 as a future enhancement that might require a mor extensive rework.
