### ISSUE TITLE
Longer Todos show ugly spacing

### ISSUE THREAD

**Issue by eggdropsoap** [pyrige/fvtt-keikaku#5]
The text spacing of a one-line Todo item looks fine and is left justified. Todo items that are long enough to word-wrap onto the next line are badly spaced to stretch the first line to fill the entire todo window. This is caused by `text-align: justify` in [keikaku.css at line 23](https://github.com/pyrige/fvtt-keikaku/blob/e1c3b43e142d21d7a037029c7b870506395a5a07/styles/keikaku.css#L23), which seems to be ignored for single-line `div`s, so it only takes effect for multi-line Todo items:

````CSS
#keikaku-todo-list .todo-description {
    text-align: justify;
````

I experimented with the dev console to change it to `text-align: left`. It looks much better for multi-line Todo items and doesn't change the display of single-line Todo items.

**Browser:** Chromium
**OS:** MacOS

**Comment by pyrige** [comment]
It does indeed look a bit weird in certain cases. I guess I can *justify* removing that line.
