### ISSUE TITLE
Text box is incredibly small

### ISSUE THREAD

**Issue by mjsuchomel** [pyrige/fvtt-keikaku#7]
You can't see what you're writing, since the description box for writing new to-do's is only two characters wide.
![](https://media.discordapp.net/attachments/722566083499786352/872593280834101269/unknown.png)

**Comment by pyrige** [comment]
That does indeed look weird. This is how it's supposed to look in the current version:
![image](https://user-images.githubusercontent.com/10303076/128293280-b0a718fd-631a-4d1d-8d8c-98d12a63dde1.png)

I'll try to look into it, but I need a bit more information:
* What version of Foundry and keikaku are you running?
* Is this in a browser (and which one) or in the desktop application?
* What other modules do you have installed? Do any of them modify the general look & feel?
* Are there any other forms in Foundry that look similarly weird?

**Comment by mjsuchomel** [comment]
I am running Foundry 0.8.8 with Keikaku 0.2.1. This is in browser (chrome, though I believe the same in Firefox).

It seems as though it's a system problem. I tried it in a new PF1e world with no other modules active, and the issue persists. However, in a clean 5e world, the issue is gone.

**Comment by pyrige** [comment]
This is indeed due to the PF1e system adding additional styling. In particular it's the [additional styling for stacked forms](https://gitlab.com/Furyspark/foundryvtt-pathfinder1/-/blob/master/less/misc.less#L1-18) that breaks things for us.
